# Must be unique in a given SonarQube instance
sonar.projectKey=NmapFastApi
sonar.organization=jaskarn
# This is the name and version displayed in the SonarQube UI. Was mandatory prior to SonarQube 6.1.
sonar.projectName=NmapFastApi
sonar.projectVersion=1.0
sonar.branch.name=main
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=app

# Disable the python tests execution and coverage on sonar for now to avoid additional errors
sonar.python.coverage.reportPaths=coverage.xml

# Code generation tools or environments will generally not be analyzed
sonar.exclusions=venv/**,**/*.db,**/*.sqlite3,tests/**
